name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make cmocka valgrind
      
      - name: Build
        run: make clean && make
      
      - name: Tests
        run: make test
      
      - name: Valgrind
        run: valgrind --leak-check=full --error-exitcode=1 ./test_builtin
