name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libcmocka-dev valgrind
      
      - name: Build
        run: make clean CFLAGS="-Wall -Wextra -Werror -pedantic"
      
      - name: Tests
        run: make test
      
      - name: Memory Check
        run: make check-mem
